---
title: "Example slide with xarigan and learnr"
subtitle: "DIME Analytics"
date: "The World Bank -- DIME | [WB Github](https://github.com/worldbank) <br> `r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ["libs/default.css", 
          "libs/metropolis.css", 
          "libs/metropolis-fonts.css",
          "libs/custom.css"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}

# Load packages
options(htmltools.dir.version = FALSE)
library(knitr)
opts_chunk$set(
  fig.align="center",  
  fig.height=4, #fig.width=6,
  # out.width="748px", #out.length="520.75px",
  dpi=300, #fig.path='Figs/',
  cache=T#, echo=F, warning=F, message=F
  )
library(hrbrthemes)
library(fontawesome)
library(xaringanExtra)
xaringanExtra::use_panelset()
xaringanExtra::use_webcam()
```

```{r xaringan-logo, echo=FALSE}
xaringanExtra::use_logo(
  image_url = "img/lightbulb.png",
  exclude_class = c("inverse", "hide_logo"),
  width = "50px"
)
```

```{css, echo = F, eval = T}
@media print {
  .has-continuation {
    display: block !important;
  }
}
```

# Demo

This is a demo slide that uses `learnr` within a xaringan presentation. 


```{r echo=FALSE}
knitr::include_app("https://rrmaximiliano.shinyapps.io/learnr-app/")
```

